<?php 
    return array(
        'site_title' => 'Thinkin Pro',
        'site_logo' => 'public/config/VZcwMtrwRvyBvwNCZzcnt86bFxYzY9e6aBMYXl1l.png',
        'site_email' => 'admin@admin.com',
        'site_icon' => 'public/config/XCphG0DUtaFvfqhhCpVKp2c5z9CWdwqLjwz3exW2.png',
        'site_copyright' => 'Thinkin Cab 2021',
        'stripe_publishable_key' => 'pk_test_PMYaUNmrK3jo5j4juAV282vy',
        'stripe_secret_key' => 'sk_test_UooZBWk1siShCS7RPfkOheMe',
        'contact_number' => '8126961804',
        'timezone' => 'Asia/Kolkata',

        'demo_mode' => '0',
        
        'store_link_android_user' => 'https://play.google.com/store/apps/details?id=com.thinkinservice.app',
        'version_android_user' => '1',
        'store_link_android_provider' => 'https://play.google.com/store/apps/details?id=com.thinkinservice.app',
        'version_android_provider' => '1',
        'store_link_ios_user' => '#',
        'version_ios_user' => '1',
        'store_link_ios_provider' => '#',
        'version_ios_provider' => '1',
        'facebook_link' => 'https://fb.com',
        'instagram_link' => 'https://instagram.com/123188',
        'twitter_link' => 'https://twitter.com',

        'social_login' => '0',
        'fb_public_key' => '123123',
        'fb_secret_key' => 'newsecretKey',
        'fb_redirect_url' => 'fb.com',
        'google_public_key' => '11936843147-5517o664rki45ceufviuhju40kvkj4ru.apps.googleusercontent.com',
        'google_secret_key' => 'w4tlMuhkr6zhn-HIObROOenI',
        'google_redirect_url' => 'http://localhost/test/public/google/success',

        'provider_accept_timeout' => '60',
        'provider_search_radius' => '40',
        'distance_map' => 'kms',

        'map_key' => 'AIzaSyChlQsXUObrzh6mT6CuohdHxz1cTK_Gi4o',
        'server_map_key' => 'AIzaSyBKE8TdSuMS_Vg748VuXwg2mjTnSm3vlrw',
        'fb_app_version' => 'v1.4.3',
        'android_sender_key' => '952820941384',

        'ios_push_environment' => 'Production',
        'ios_push_user_permission' => 'public/config/9aiqrJWqUiRyQBl6eYVyGlsFjBhTvyv8kixCPWH5.docx',
        'ios_push_provider_permission' => 'public/config/NpDWIOK557hWufF3GnAM2veKHioKIEbRJ5kbmLg2.docx',
        'ios_push_password' => 'Push Password',
        'android_push_key' => 'AAAA3diNwkg:APA91bG6iKJ8ffKrjp1XYh0hQ0mHzJJHPYYcO8wFT9ORccz4mBfi4nNw2O6eWNv4akdp0Y4XdqYb4MdnDSvd0AQ-BUzJ26bmpJ5cz0DtkOBKV-BakdoP48XhQ73_vZl_kEClQ3p_p6te',

        'send_mail' => '1',
        'mail_driver' => '',
        'mail_host' => '',
        'mail_port' => '',
        'mail_username' => '',
        'mail_password' => '',
        'mail_from_address' => '',
        'mail_from_name' => '',
        'mail_encryption' => '',

        'referral' => '1',
        'referral_count' => '1',
        'referral_amount' => '500',
        'booking_id_prefix' => 'Dragon#',
        'currency' => '₹',
        'currency_exchange_key' => 'e921e736532e4f59bb65eae235860fcf',

        'cash_payment' => '1',
        'online_payment' => '1',
        'stripe_payment' => '0',

        'payment_daily_target' => '20',
        'tax_percentage' => '5',
        'commission_percentage' => '5',
        'agent_commission_percentage' => '5',
        'peak_percentage' => '50',
        'minimum_negative_balance' => '-100',
        'cancel_charge' => '50',

        'rental' => '1',
        'outstation' => '1',
        'manual_request' => '0',
        'track_distance' => '1',
        'ride_toll' => '0',
        'ride_otp' => '0',
        'outstation_base_km' => '1',
        'limit_message' => 'Hey! Not too fast. You have exceeded your daily limit. Please, try again later. Thank you.',
        'broadcast_request' => '1',
    );